### ISSUE TITLE
WindowsError: exception: access violation reading 0x00000007

### ISSUE THREAD

**Issue by remembermyhentai** [dc740/AutoHotPy#1]
UPD: issue fixed by installing python 2.7 x64

**Comment by darenx** [comment]
Hello I'm getting this error when I try to run Example-GameCombo.py and others Examples.
Traceback (most recent call last):
  File "C:\Python\AutoHotPy-master\Example1-GameCombo.py", line 51, in <module>
    auto.start()                                #Now that everything is registered we should start runnin the program
  File "C:\Python\AutoHotPy-master\AutoHotPy.py", line 546, in start
    self.interception = InterceptionWrapper()
  File "C:\Python\AutoHotPy-master\InterceptionWrapper.py", line 171, in __init__
    self.interceptionDll = ctypes.WinDLL ("./interception.dll")
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found.

**Comment by rymka1989** [comment]
> UPD: issue fixed by installing python 2.7 x64

I had the same trouble.
I had Windows x64 and Python3.7 32-bit, i've installed Python3.7 64-bit and everything is ok.
So AutoHotPy works ok with Python3+
