### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'autohotpy'

### ISSUE THREAD

**Issue by 6ftClaud** [dc740/AutoHotPy#13]
Hey,
I'm coming over from C++ to Python to write a simple bot for Lineage II. I'm using this AutoHotPy because the game blocks artificial input and I'm hoping this could fix this. Problem is, I'm getting a lot of different errors (some I've fixed and some are beyond my knowledge at the moment). As a last attempt, I'm trying this.
The error is:

Game window found.
Traceback (most recent call last):
  File "C:\Users\klaud\source\repos\ClaudBot\main.py", line 88, in <module>
    main()
  File "C:\Users\klaud\source\repos\ClaudBot\main.py", line 77, in main
    action.attack()
  File "C:\Users\klaud\source\repos\ClaudBot\main.py", line 61, in attack
    self.autohotpy.moveMouseToPosition(x, y)
AttributeError: 'Bot' object has no attribute 'autohotpy'

I'm not sure how to fix this, maybe someone could help? Attaching zip file. 
[main.zip](https://github.com/dc740/AutoHotPy/files/4321336/main.zip)

Offtopic: I've learned a hella lot of Python these couple of days.

**Comment by 6ftClaud** [comment]
And also how do I pass the "self" argument to a autohotpy leftClick function?
